### ISSUE TITLE
Qwen-Image-Edit not working properly...

### ISSUE THREAD

**Issue by bobs2002** [Haoming02/sd-webui-forge-classic#278]
Hi, I've updated NEO and I'm trying to send a doggie into space, but nothing changes, I'm trying different QWEN -EDIT models, but nothing happens, what am I doing wrong?

<img width="1874" height="909" alt="Image" src="https://github.com/user-attachments/assets/282ec29e-493b-4ef7-87ba-bf769d393ba4" />
<img width="1869" height="887" alt="Image" src="https://github.com/user-attachments/assets/a2e9a71b-2369-467b-97fa-006f42ce72d7" />

**Comment by Haoming02** [comment]
tbh "a space" doesn't really make much sense 

<p align="center"><img src="https://github.com/user-attachments/assets/8449d82d-a05a-4df3-89cb-d43e22dad103"></p>

**Comment by bobs2002** [comment]
Yes, but it seems to me that it's not about promptness, I changed three models of QWEN - EDIT nothing helps

<img width="1863" height="915" alt="Image" src="https://github.com/user-attachments/assets/6e75fec6-5a7d-4235-b61f-6fd219600ccb" />

**Comment by ivancollider** [comment]
Flux Kontext 


Change  background to a space


<img width="1913" height="933" alt="Image" src="https://github.com/user-attachments/assets/73e68bce-aee7-4d11-9811-bd10e74da292" />

Change the background to outer space

<img width="1911" height="940" alt="Image" src="https://github.com/user-attachments/assets/c958981f-6eed-4249-a737-78d90336a76d" />

Yeah, Qwen struggles to fully effect the image, very strange

**Comment by Haoming02** [comment]
Maybe I missed something in the pipeline... I will investigate more tomorrow.

Currently fixing Inpainting...

**Comment by CemreKArtworkss** [comment]
Yeah, Qwen image edit not working :(

**Comment by Haoming02** [comment]
***Ladies and gentlemen, this has been fixed~***

~~Why didn't ComfyUI put the codes at the same place smh~~

**Comment by ivancollider** [comment]
Man, wow, you really fixed it.
I can't speak for the other guys, but it works for me.

Thank you! We're so lucky to have a developer like you!

**Comment by bobs2002** [comment]
> _**Ladies and gentlemen, this has been fixed~**_
> 
> ~Why didn't ComfyUI put the codes at the same place smh~

<img width="1876" height="921" alt="Image" src="https://github.com/user-attachments/assets/27e5b8f8-091c-41c0-9185-8644802597c0" />

I updated it today, but when generating it, I get this error: RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: struct c10::Half instead.

**Comment by Haoming02** [comment]
oops, fixed :P

**Comment by bobs2002** [comment]
> упс, исправил :Р

I updated, but it seems nothing has changed, still the same error.

**Comment by CemreKArtworkss** [comment]
I'm trying now.
